---
- name: Setup facts for future usage
  hosts: all
  strategy: free

- name: Configure app servers
  hosts: app
  serial: 1
  roles:
    - ansible-gitlab-ci-aws-app

- name: Configure gitaly servers
  hosts: gitaly
  roles:
    - ansible-gitlab-ci-aws-gitaly

- name: Configure runner servers
  hosts: runner
  roles:
    - ansible-gitlab-ci-aws-runner
