---
- import_playbook: terraform_output.yml

- name: Configure app servers
  hosts: app
  tasks:
    - ping:

- name: Configure gitaly servers
  hosts: gitaly
  tasks:
    - ping:

- name: Configure runner servers
  hosts: runner
  tasks:
    - ping:
