- name: Load terraform outputs as localhost inventory variables
  hosts: localhost
  connection: local
  become: false
  vars:
    aws_profile: gitlab-ci-aws
  tasks:
    - name: Get rds outputs
      tf_output:
        bucket: "{{ aws_profile }}-terraform-state"
        object: "{{ env }}/rds/terraform.tfstate"
        aws_profile: "{{ aws_profile }}"
      register: rds

    - name: Set rds output
      set_fact:
        rds: "{{ rds.vars }}"

    - name: Get rdedis outputs
      tf_output:
        bucket: "{{ aws_profile }}-terraform-state"
        object: "{{ env }}/redis/terraform.tfstate"
        aws_profile: "{{ aws_profile }}"
      register: redis

    - name: Set redis output
      set_fact:
        redis: "{{ redis.vars }}"
