name: 'Runs production environment'

on:
  push:
    branches:
      - master

env:
  tg_version: '0.26.2'
defaults:
  run:
    shell: bash
    working-directory: 'envs/prod'

jobs:
  terragrunt:
    name: 'Terragrunt Apply'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v0.1.0
        with:
          terragrunt_version: ${{ env.tg_version }}
      - name: 'Terragrunt Apply'
        run: terragrunt apply-all --terragrunt-non-interactive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
